// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WP.Repositories.Models;

[Table("Style")]
public partial class Style
{
    [Key]
    [StringLength(30)]
    public string StyleId { get; set; }

    [Required]
    [StringLength(100)]
    public string StyleName { get; set; }

    [Required]
    [StringLength(250)]
    public string StyleDescription { get; set; }

    [StringLength(160)]
    public string OriginalCountry { get; set; }

    [InverseProperty("Style")]
    public virtual ICollection<WatercolorsPainting> WatercolorsPaintings { get; set; } = new List<WatercolorsPainting>();
}