// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Table("Brand")]
public partial class Brand
{
    [Key]
    [Column("BrandID")]
    public int BrandId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string BrandName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Country { get; set; }

    public int? FoundedYear { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Website { get; set; }

    [InverseProperty("Brand")]
    public virtual ICollection<Handbag> Handbags { get; set; } = new List<Handbag>();
}