// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

[Table("Handbag")]
public partial class Handbag
{
    [Key]
    [Column("HandbagID")]
    [Required]
    public int HandbagId { get; set; }

    [Column("BrandID")]
    [Required]
    public int? BrandId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    [RegularExpression(@"^([A-Z][a-zA-Z0-9#]*\s?)+$")]
    public string ModelName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    [Required]
    public string Material { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [Required]
    public string Color { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    [Required]
    [Range(0, double.MaxValue, ErrorMessage = "Price must be greater than or equal to 0")]
    public decimal? Price { get; set; }

    [Required]
    [Range(0, double.MaxValue, ErrorMessage = "Price must be greater than or equal to 0")]
    public int? Stock { get; set; }

    [Required]
    public DateOnly? ReleaseDate { get; set; }

    [ForeignKey("BrandId")]
    [InverseProperty("Handbags")]
    public virtual Brand Brand { get; set; }
}